### ISSUE TITLE
spec-v3, cannot load project

### ISSUE THREAD

**Issue by martinschorb** [mobie/covid-if-project#12]
Hi,

`spec-v3` does not load properly for me:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: Image nuclei_WellE06_0000_E06_nuclei_plate_nuclei is not part of the current data.
	at org.embl.mobie.viewer.DataStore.getImage(DataStore.java:42)
	at org.embl.mobie.viewer.image.RegionLabelImage.createLabelImage(RegionLabelImage.java:79)
	at org.embl.mobie.viewer.image.RegionLabelImage.<init>(RegionLabelImage.java:67)
	at org.embl.mobie.viewer.view.ViewManager.initData(ViewManager.java:501)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:266)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:276)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:202)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:148)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectBranchCommand.run(OpenMoBIEProjectBranchCommand.java:62)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

and then, when loading a view:

```
Exception in thread "Thread-11" java.lang.RuntimeException: Image nuclei_WellA01_0000_A01_nuclei_plate_nuclei is not part of the current data.
	at org.embl.mobie.viewer.DataStore.getImage(DataStore.java:42)
	at org.embl.mobie.viewer.image.RegionLabelImage.createLabelImage(RegionLabelImage.java:79)
	at org.embl.mobie.viewer.image.RegionLabelImage.<init>(RegionLabelImage.java:67)
	at org.embl.mobie.viewer.view.ViewManager.initData(ViewManager.java:501)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:266)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
@constantinpape 

I think this is a spec issue: `Image nuclei_WellA01_0000_A01_nuclei_plate_nuclei`
Such names should not occur anymore.

**Comment by constantinpape** [comment]
Should be fixed now @tischi. Can you double checkk?

**Comment by tischi** [comment]
Could you let me know which view?

**Comment by constantinpape** [comment]
Ok, we checked and it's fixed now.
