### ISSUE TITLE
cannot load view

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#13]
```
new MoBIE( "https://github.com/mobie/covid-if-project", MoBIESettings.settings().gitProjectBranch( "mobie3" ).view( "single_well_with_nucleus_segmentation" ) ); 
```

errors with

```
Exception in thread "main" java.lang.RuntimeException: Image marker_tophat_WellF09_0000_single_well-0 is not part of the current data.
	at org.embl.mobie.viewer.DataStore.getImage(DataStore.java:42)
	at org.embl.mobie.viewer.image.RegionLabelImage.createLabelImage(RegionLabelImage.java:79)
	at org.embl.mobie.viewer.image.RegionLabelImage.<init>(RegionLabelImage.java:67)
	at org.embl.mobie.viewer.view.ViewManager.initData(ViewManager.java:505)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:270)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:276)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:202)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:148)
	at projects.OpenRemoteCovidIF.main(OpenRemoteCovidIF.java:44)
```

@constantinpape could you check whether this view is still OK?

To me the `-0` in `Image marker_tophat_WellF09_0000_single_well-0` looks suspicious...

**Comment by constantinpape** [comment]
Should also be fixed. Can you check it?

**Comment by tischi** [comment]
It loads not without error, but I cannot see the images....
Don't know why yet.

**Comment by constantinpape** [comment]
It works now.
